# Operating System
UBUNTU_VERSION="26.04"
# Python
PYTHON_VERSION="3.14"
# Node.js
NODE_VERSION="24"
# Java
JAVA_VERSION="21"
# Flutter
FLUTTER_VERSION="stable"
# PostgreSQL
POSTGRES_VERSION="17"
# Redis
REDIS_VERSION="8"
# Docker
DOCKER_CHANNEL="stable"
